spring:
  application:
    name: gateway-server
    
  cloud:
    gateway:
      discovery:
        locator: #service discover에 등록된 서비스를 기반으로 gatewa가 경로를
          enabled: true #생성하도록 설정한다
          lower-case-service-id: true
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway GlobalFilter
#            preLogger: true
#            postLogger: true
      routes:
        - id: blog-service
          uri: http://localhost:9000
          predicates:
            - Path=/blog/**
        - id: member-service
          uri: http://localhost:9091
          predicates:
            - Path=/member/**
          filters:
            - AddRequestHeader=member-service-request, member-service-request-header
            - AddResponseHeader=member-service-response, member-service-response-header

server:
  port: 8072

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/ 