server:
  port: 9000
 
spring:  
  config:
    import: optional:configserver:http://localhost:8888
     
  application:
    name: blog-service
    
  profiles:
    default: blog-service
    
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
 
        
        
eureka: 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/         
 