#src/main/resources/bootstrap.yml
spring:
  application:
    name: config-server
  profiles:
    active: native #파일 시스템 기반의 저장소를 사용할 때 native 프로파일을 사용한다
  cloud:
    config:
      server:
        native:
          #uri: https://github.com/kimhyomin97/spring-cloud # (FILE_PAPTH)구성 파일이 저장된 검색 위치를 설정
          search-locations: file:///Users/hyomin/dev/MyRepo

#src/main/resources/applicaton.yaml
server:
  port: 8888 # Config Server가 수신 대기하는 포트

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
