spring:
  config:
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://config-server:8888
  application:
    name: blog-service
  profiles:
    default: blog-service

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"